# Generated by Django 4.2.4 on 2023-08-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=50)),
                ('born_date', models.TextField(max_length=50)),
                ('born_location', models.TextField(max_length=350)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=3000)),
                ('tags', models.TextField(max_length=100)),
                ('author', models.ManyToManyField(to='quotes_app.author')),
            ],
        ),
    ]
